import json
import os
import sqlite3
from contextlib import contextmanager
from datetime import UTC, datetime
from collections.abc import Iterator
from typing import Any
from app.odds_buckets import odds_bucket_for_value

try:
    import psycopg
    from psycopg.rows import dict_row
except ImportError:  # pragma: no cover
    psycopg = None
    dict_row = None


DB_PATH = os.getenv("BETTING_DB_PATH", "betting_tracker.sqlite3")
DATABASE_URL = os.getenv("DATABASE_URL", "").strip()
SPORT_HISTORY_RESETS_SETTING = "sport_history_resets"
IDENTITY_TABLES = {
    "picks",
    "odds_snapshots",
    "pick_evaluations",
    "telegram_publications",
    "telegram_publication_items",
}


def _is_postgres(db_path: str = DB_PATH) -> bool:
    if db_path != DB_PATH:
        return False
    return bool(DATABASE_URL)


def _adapt_sql(query: str) -> str:
    return query.replace("?", "%s")


class CompatCursor:
    def __init__(self, cursor: Any, backend: str, lastrowid: int | None = None):
        self._cursor = cursor
        self._backend = backend
        self.lastrowid = lastrowid

    def fetchone(self):
        row = self._cursor.fetchone()
        return row

    def fetchall(self):
        return self._cursor.fetchall()


class CompatConnection:
    def __init__(self, raw: Any, backend: str):
        self._raw = raw
        self._backend = backend
        self.row_factory = getattr(raw, "row_factory", None)

    def execute(self, query: str, params: tuple | list = ()):
        if self._backend == "sqlite":
            cursor = self._raw.execute(query, params)
            return CompatCursor(cursor, self._backend, getattr(cursor, "lastrowid", None))

        if psycopg is None:
            raise RuntimeError("psycopg no esta instalado")

        q = _adapt_sql(query)
        lastrowid = None
        match = None
        normalized = query.strip().lower()
        if normalized.startswith("insert into"):
            parts = normalized.split()
            if len(parts) >= 3:
                table_name = parts[2].strip('"')
                if table_name in IDENTITY_TABLES and "returning" not in normalized:
                    q = f"{q} RETURNING id"
                    match = table_name

        cursor = self._raw.cursor(row_factory=dict_row)
        cursor.execute(q, params)
        if match:
            row = cursor.fetchone()
            if row:
                lastrowid = int(row["id"])
        return CompatCursor(cursor, self._backend, lastrowid)

    def commit(self) -> None:
        self._raw.commit()

    def close(self) -> None:
        self._raw.close()


@contextmanager
def conectar(db_path: str = DB_PATH) -> Iterator[Any]:
    if _is_postgres(db_path):
        if psycopg is None:
            raise RuntimeError("Para usar Postgres instala psycopg[binary]")
        conn = psycopg.connect(DATABASE_URL, row_factory=dict_row)
        compat = CompatConnection(conn, "postgres")
        try:
            yield compat
        finally:
            compat.close()
        return

    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    compat = CompatConnection(conn, "sqlite")

    try:
        yield compat
    finally:
        compat.close()


def _asegurar_columna(
    conn: Any,
    table: str,
    column: str,
    definition: str,
) -> None:
    if isinstance(conn, CompatConnection) and conn._backend == "postgres":
        columnas = {
            row["column_name"]
            for row in conn.execute(
                """
                SELECT column_name
                FROM information_schema.columns
                WHERE table_schema = 'public' AND table_name = %s
                """,
                (table,),
            ).fetchall()
        }
        if column not in columnas:
            conn.execute(f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS {column} {definition}")
        return

    columnas = {
        row["name"]
        for row in conn.execute(f"PRAGMA table_info({table})").fetchall()
    }

    if column not in columnas:
        conn.execute(f"ALTER TABLE {table} ADD COLUMN {column} {definition}")


def inicializar_db(db_path: str = DB_PATH) -> None:
    with conectar(db_path) as conn:
        if isinstance(conn, CompatConnection) and conn._backend == "postgres":
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS picks (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    created_at TEXT NOT NULL,
                    event_id TEXT,
                    commence_time TEXT,
                    sport_key TEXT,
                    sport_label TEXT,
                    league_key TEXT,
                    league_label TEXT,
                    partido TEXT NOT NULL,
                    equipo TEXT NOT NULL,
                    tipo_resultado TEXT,
                    casa TEXT,
                    mercado TEXT,
                    cuota DOUBLE PRECISION NOT NULL,
                    cuota_minima DOUBLE PRECISION,
                    probabilidad_mercado DOUBLE PRECISION,
                    probabilidad_elo DOUBLE PRECISION,
                    probabilidad_modelo DOUBLE PRECISION,
                    valor_esperado DOUBLE PRECISION,
                    margen_cuota DOUBLE PRECISION,
                    kelly_fraccional DOUBLE PRECISION,
                    stake_pct_bankroll DOUBLE PRECISION,
                    importe_sugerido DOUBLE PRECISION,
                    stake DOUBLE PRECISION,
                    recomendacion TEXT,
                    motivo TEXT,
                    quality_score INTEGER,
                    elite_pick INTEGER NOT NULL DEFAULT 0,
                    estado TEXT NOT NULL DEFAULT 'pendiente',
                    resultado TEXT,
                    closing_odds DOUBLE PRECISION,
                    profit_loss DOUBLE PRECISION,
                    recommended_by_bot INTEGER NOT NULL DEFAULT 1,
                    auto_eval_eligible INTEGER NOT NULL DEFAULT 1,
                    raw_json TEXT NOT NULL
                )
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS odds_snapshots (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    created_at TEXT NOT NULL,
                    event_id TEXT,
                    commence_time TEXT,
                    sport_key TEXT,
                    sport_label TEXT,
                    league_key TEXT,
                    league_label TEXT,
                    partido TEXT,
                    bookmaker TEXT,
                    market_key TEXT,
                    outcome_name TEXT,
                    outcome_point DOUBLE PRECISION,
                    price DOUBLE PRECISION,
                    raw_json TEXT NOT NULL
                )
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS pick_evaluations (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    pick_id INTEGER NOT NULL UNIQUE REFERENCES picks(id),
                    created_at TEXT NOT NULL,
                    event_id TEXT,
                    sport_label TEXT,
                    league_label TEXT,
                    mercado TEXT,
                    casa TEXT,
                    resultado TEXT NOT NULL,
                    closing_odds DOUBLE PRECISION,
                    price_taken DOUBLE PRECISION,
                    value_captured DOUBLE PRECISION,
                    clv_pct DOUBLE PRECISION,
                    quality_score INTEGER,
                    reliability_score INTEGER,
                    execution_score INTEGER,
                    ranking_score INTEGER,
                    elite_tier TEXT,
                    payload_json TEXT NOT NULL
                )
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS app_settings (
                    key TEXT PRIMARY KEY,
                    value TEXT NOT NULL,
                    updated_at TEXT NOT NULL
                )
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS telegram_publications (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    created_at TEXT NOT NULL,
                    publication_type TEXT NOT NULL,
                    sport_label TEXT,
                    league_label TEXT,
                    total_picks INTEGER NOT NULL DEFAULT 0,
                    total_stakazos INTEGER NOT NULL DEFAULT 0,
                    payload_json TEXT NOT NULL
                )
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS telegram_publication_items (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    publication_id INTEGER NOT NULL REFERENCES telegram_publications(id),
                    pick_id INTEGER,
                    telegram_message_id INTEGER,
                    message_kind TEXT NOT NULL,
                    text TEXT NOT NULL
                )
                """
            )
        else:
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS picks (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    created_at TEXT NOT NULL,
                    event_id TEXT,
                    commence_time TEXT,
                    sport_key TEXT,
                    sport_label TEXT,
                    league_key TEXT,
                    league_label TEXT,
                    partido TEXT NOT NULL,
                    equipo TEXT NOT NULL,
                    tipo_resultado TEXT,
                    casa TEXT,
                    mercado TEXT,
                    cuota REAL NOT NULL,
                    cuota_minima REAL,
                    probabilidad_mercado REAL,
                    probabilidad_elo REAL,
                    probabilidad_modelo REAL,
                    valor_esperado REAL,
                    margen_cuota REAL,
                    kelly_fraccional REAL,
                    stake_pct_bankroll REAL,
                    importe_sugerido REAL,
                    stake REAL,
                    recomendacion TEXT,
                    motivo TEXT,
                    quality_score INTEGER,
                    elite_pick INTEGER NOT NULL DEFAULT 0,
                    estado TEXT NOT NULL DEFAULT 'pendiente',
                    resultado TEXT,
                    closing_odds REAL,
                    profit_loss REAL,
                    recommended_by_bot INTEGER NOT NULL DEFAULT 1,
                    auto_eval_eligible INTEGER NOT NULL DEFAULT 1,
                    raw_json TEXT NOT NULL
                )
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS odds_snapshots (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    created_at TEXT NOT NULL,
                    event_id TEXT,
                    commence_time TEXT,
                    sport_key TEXT,
                    sport_label TEXT,
                    league_key TEXT,
                    league_label TEXT,
                    partido TEXT,
                    bookmaker TEXT,
                    market_key TEXT,
                    outcome_name TEXT,
                    outcome_point REAL,
                    price REAL,
                    raw_json TEXT NOT NULL
                )
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS pick_evaluations (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    pick_id INTEGER NOT NULL UNIQUE,
                    created_at TEXT NOT NULL,
                    event_id TEXT,
                    sport_label TEXT,
                    league_label TEXT,
                    mercado TEXT,
                    casa TEXT,
                    resultado TEXT NOT NULL,
                    closing_odds REAL,
                    price_taken REAL,
                    value_captured REAL,
                    clv_pct REAL,
                    quality_score INTEGER,
                    reliability_score INTEGER,
                    execution_score INTEGER,
                    ranking_score INTEGER,
                    elite_tier TEXT,
                    payload_json TEXT NOT NULL,
                    FOREIGN KEY(pick_id) REFERENCES picks(id)
                )
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS app_settings (
                    key TEXT PRIMARY KEY,
                    value TEXT NOT NULL,
                    updated_at TEXT NOT NULL
                )
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS telegram_publications (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    created_at TEXT NOT NULL,
                    publication_type TEXT NOT NULL,
                    sport_label TEXT,
                    league_label TEXT,
                    total_picks INTEGER NOT NULL DEFAULT 0,
                    total_stakazos INTEGER NOT NULL DEFAULT 0,
                    payload_json TEXT NOT NULL
                )
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS telegram_publication_items (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    publication_id INTEGER NOT NULL,
                    pick_id INTEGER,
                    telegram_message_id INTEGER,
                    message_kind TEXT NOT NULL,
                    text TEXT NOT NULL,
                    FOREIGN KEY(publication_id) REFERENCES telegram_publications(id)
                )
                """
            )
        _asegurar_columna(conn, "picks", "sport_key", "TEXT")
        _asegurar_columna(conn, "picks", "sport_label", "TEXT")
        _asegurar_columna(conn, "picks", "league_key", "TEXT")
        _asegurar_columna(conn, "picks", "league_label", "TEXT")
        _asegurar_columna(conn, "picks", "quality_score", "INTEGER")
        _asegurar_columna(conn, "picks", "elite_pick", "INTEGER NOT NULL DEFAULT 0")
        _asegurar_columna(conn, "picks", "recommended_by_bot", "INTEGER NOT NULL DEFAULT 1")
        _asegurar_columna(conn, "picks", "auto_eval_eligible", "INTEGER NOT NULL DEFAULT 1")
        _asegurar_columna(conn, "odds_snapshots", "sport_key", "TEXT")
        _asegurar_columna(conn, "odds_snapshots", "sport_label", "TEXT")
        _asegurar_columna(conn, "odds_snapshots", "league_key", "TEXT")
        _asegurar_columna(conn, "odds_snapshots", "league_label", "TEXT")
        conn.commit()


def obtener_setting(key: str, default: str | None = None, db_path: str = DB_PATH) -> str | None:
    inicializar_db(db_path)

    with conectar(db_path) as conn:
        row = conn.execute("SELECT value FROM app_settings WHERE key = ?", (key,)).fetchone()

    return row["value"] if row else default


def guardar_setting(key: str, value: str, db_path: str = DB_PATH) -> None:
    inicializar_db(db_path)
    ahora = datetime.now(UTC).isoformat()

    with conectar(db_path) as conn:
        conn.execute(
            """
            INSERT INTO app_settings (key, value, updated_at)
            VALUES (?, ?, ?)
            ON CONFLICT(key) DO UPDATE SET
                value = excluded.value,
                updated_at = excluded.updated_at
            """,
            (key, value, ahora),
        )
        conn.commit()


def _parse_iso_datetime(value: Any) -> datetime | None:
    text = str(value or "").strip()
    if not text:
        return None
    try:
        if text.endswith("Z"):
            text = text[:-1] + "+00:00"
        dt = datetime.fromisoformat(text)
        if dt.tzinfo is None:
            return dt.replace(tzinfo=UTC)
        return dt.astimezone(UTC)
    except ValueError:
        return None


def obtener_resets_historial_deportes(db_path: str = DB_PATH) -> dict[str, str]:
    raw = obtener_setting(SPORT_HISTORY_RESETS_SETTING, "{}", db_path=db_path) or "{}"
    try:
        data = json.loads(raw)
    except json.JSONDecodeError:
        return {}

    if not isinstance(data, dict):
        return {}

    sanitized: dict[str, str] = {}
    for sport_label, cutoff in data.items():
        sport = str(sport_label or "").strip()
        cutoff_text = str(cutoff or "").strip()
        if not sport or not cutoff_text:
            continue
        if _parse_iso_datetime(cutoff_text) is None:
            continue
        sanitized[sport] = cutoff_text
    return sanitized


def guardar_reset_historial_deporte(
    sport_label: str,
    cutoff_iso: str | None = None,
    db_path: str = DB_PATH,
) -> dict[str, str]:
    sport = str(sport_label or "").strip()
    if not sport:
        raise ValueError("sport_label es obligatorio")

    cutoff_text = str(cutoff_iso or datetime.now(UTC).isoformat()).strip()
    cutoff_dt = _parse_iso_datetime(cutoff_text)
    if cutoff_dt is None:
        raise ValueError("cutoff_iso invalido")

    resets = obtener_resets_historial_deportes(db_path=db_path)
    resets[sport] = cutoff_dt.isoformat()
    guardar_setting(
        SPORT_HISTORY_RESETS_SETTING,
        json.dumps(resets, ensure_ascii=False),
        db_path=db_path,
    )
    return resets


def eliminar_reset_historial_deporte(
    sport_label: str,
    db_path: str = DB_PATH,
) -> dict[str, str]:
    sport = str(sport_label or "").strip()
    resets = obtener_resets_historial_deportes(db_path=db_path)
    if sport in resets:
        del resets[sport]
        guardar_setting(
            SPORT_HISTORY_RESETS_SETTING,
            json.dumps(resets, ensure_ascii=False),
            db_path=db_path,
        )
    return resets


def filtrar_registros_por_reset_deporte(
    rows: list[dict[str, Any]],
    *,
    db_path: str = DB_PATH,
    sport_getter: Any = None,
    created_field: str = "created_at",
) -> list[dict[str, Any]]:
    resets = obtener_resets_historial_deportes(db_path=db_path)
    if not resets:
        return list(rows)

    filtered: list[dict[str, Any]] = []
    for row in rows:
        if callable(sport_getter):
            sport = str(sport_getter(row) or "").strip()
        else:
            sport = str(row.get("sport_label") or "").strip()

        cutoff_text = resets.get(sport)
        if not cutoff_text:
            filtered.append(row)
            continue

        created_dt = _parse_iso_datetime(row.get(created_field))
        cutoff_dt = _parse_iso_datetime(cutoff_text)
        if created_dt is None or cutoff_dt is None or created_dt >= cutoff_dt:
            filtered.append(row)

    return filtered


def obtener_bankroll(default: float = 25, db_path: str = DB_PATH) -> float:
    value = obtener_setting("bankroll_actual", str(default), db_path=db_path)

    try:
        return round(float(value), 2)
    except (TypeError, ValueError):
        return round(default, 2)


def actualizar_bankroll(bankroll: float, db_path: str = DB_PATH) -> float:
    if bankroll < 0:
        raise ValueError("bankroll debe ser mayor o igual que 0")

    bankroll = round(float(bankroll), 2)
    guardar_setting("bankroll_actual", str(bankroll), db_path=db_path)
    return bankroll


def guardar_snapshot_cuotas(
    partidos: list[dict[str, Any]],
    db_path: str = DB_PATH,
) -> int:
    inicializar_db(db_path)
    ahora = datetime.now(UTC).isoformat()
    guardadas = 0

    with conectar(db_path) as conn:
        for partido in partidos:
            home = partido.get("home_team")
            away = partido.get("away_team")
            partido_nombre = f"{home} vs {away}" if home and away else None

            for bookmaker in partido.get("bookmakers", []):
                casa = bookmaker.get("title")

                for market in bookmaker.get("markets", []):
                    market_key = market.get("key")

                    for outcome in market.get("outcomes", []):
                        price = outcome.get("price")

                        if not price:
                            continue

                        conn.execute(
                            """
                            INSERT INTO odds_snapshots (
                                created_at, event_id, commence_time, sport_key, sport_label,
                                league_key, league_label, partido, bookmaker,
                                market_key, outcome_name, outcome_point, price, raw_json
                            )
                            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                            """,
                            (
                                ahora,
                                partido.get("id"),
                                partido.get("commence_time"),
                                partido.get("sport_key"),
                                partido.get("sport_label"),
                                partido.get("league_key"),
                                partido.get("league_label"),
                                partido_nombre,
                                casa,
                                market_key,
                                outcome.get("name"),
                                outcome.get("point"),
                                float(price),
                                json.dumps({
                                    "event_id": partido.get("id"),
                                    "commence_time": partido.get("commence_time"),
                                    "sport_key": partido.get("sport_key"),
                                    "sport_label": partido.get("sport_label"),
                                    "league_key": partido.get("league_key"),
                                    "league_label": partido.get("league_label"),
                                    "partido": partido_nombre,
                                    "bookmaker": casa,
                                    "market": market_key,
                                    "outcome": outcome,
                                }, ensure_ascii=False),
                            ),
                        )
                        guardadas += 1

        conn.commit()

    return guardadas


def guardar_recomendaciones(recomendaciones: list[dict[str, Any]], db_path: str = DB_PATH) -> int:
    return len(guardar_recomendaciones_unicas(recomendaciones, db_path=db_path, solo_nuevas=True))


def _valor_equivalente(value: Any) -> str:
    if value is None:
        return ""

    if isinstance(value, float):
        return f"{value:.4f}"

    return str(value).strip().lower()


def _fingerprint_pick_data(data: dict[str, Any]) -> tuple[str, ...]:
    return (
        _valor_equivalente(data.get("event_id")),
        _valor_equivalente(data.get("sport_key")),
        _valor_equivalente(data.get("league_key")),
        _valor_equivalente(data.get("partido")),
        _valor_equivalente(data.get("equipo_raw") or data.get("equipo")),
        _valor_equivalente(data.get("mercado")),
        _valor_equivalente(data.get("tipo_resultado_raw") or data.get("tipo_resultado")),
        _valor_equivalente(data.get("casa")),
        _valor_equivalente(data.get("outcome_point")),
        _valor_equivalente(data.get("outcome_description")),
    )


def _insertar_pick(conn: sqlite3.Connection, rec: dict[str, Any], created_at: str) -> dict[str, Any] | None:
    if rec.get("importe_sugerido", 0) <= 0:
        return None

    cursor = conn.execute(
        """
        INSERT INTO picks (
            created_at, event_id, commence_time, sport_key, sport_label,
            league_key, league_label, partido, equipo, tipo_resultado,
            casa, mercado, cuota, cuota_minima, probabilidad_mercado, probabilidad_elo,
            probabilidad_modelo, valor_esperado, margen_cuota, kelly_fraccional,
            stake_pct_bankroll, importe_sugerido, stake, recomendacion, motivo,
            quality_score, elite_pick, recommended_by_bot, auto_eval_eligible, raw_json
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            created_at,
            rec.get("event_id"),
            rec.get("commence_time"),
            rec.get("sport_key"),
            rec.get("sport_label"),
            rec.get("league_key"),
            rec.get("league_label"),
            rec.get("partido"),
            rec.get("equipo"),
            rec.get("tipo_resultado"),
            rec.get("casa"),
            rec.get("mercado"),
            rec.get("cuota_apuesta", rec.get("cuota_pinnacle")),
            rec.get("cuota_minima_aceptable"),
            rec.get("probabilidad_mercado"),
            rec.get("probabilidad_elo"),
            rec.get("probabilidad_modelo"),
            rec.get("valor_esperado"),
            rec.get("margen_cuota"),
            rec.get("kelly_fraccional"),
            rec.get("stake_pct_bankroll"),
            rec.get("importe_sugerido"),
            rec.get("stake"),
            rec.get("recomendacion"),
            rec.get("motivo"),
            rec.get("quality_score"),
            1 if rec.get("elite_pick") else 0,
            1 if rec.get("recommended_by_bot", True) else 0,
            1 if rec.get("auto_eval_eligible", True) else 0,
            json.dumps(rec, ensure_ascii=False),
        ),
    )
    row = conn.execute("SELECT * FROM picks WHERE id = ?", (cursor.lastrowid,)).fetchone()
    return dict(row) if row else None


def guardar_recomendaciones_unicas(
    recomendaciones: list[dict[str, Any]],
    db_path: str = DB_PATH,
    solo_nuevas: bool = False,
) -> list[dict[str, Any]]:
    inicializar_db(db_path)
    ahora = datetime.now(UTC).isoformat()

    with conectar(db_path) as conn:
        pendientes = [dict(row) for row in conn.execute("SELECT * FROM picks WHERE estado = 'pendiente'").fetchall()]
        fingerprints_pendientes = {
            _fingerprint_pick_data(_raw_pick(row) | row): row
            for row in pendientes
        }
        salida: list[dict[str, Any]] = []

        for rec in recomendaciones:
            if rec.get("importe_sugerido", 0) <= 0:
                continue

            fingerprint = _fingerprint_pick_data(rec)
            existente = fingerprints_pendientes.get(fingerprint)

            if existente is not None:
                if not solo_nuevas:
                    salida.append(existente)
                continue

            creado = _insertar_pick(conn, rec, created_at=ahora)
            if creado is None:
                continue

            fingerprints_pendientes[fingerprint] = creado
            salida.append(creado)

        conn.commit()

    return salida


def guardar_apuesta_real(
    recomendacion: dict[str, Any],
    importe_real: float,
    db_path: str = DB_PATH,
) -> dict[str, Any] | None:
    if importe_real <= 0:
        raise ValueError("importe_real debe ser mayor que 0")

    rec = recomendacion.copy()
    rec["importe_modelo_sugerido"] = rec.get("importe_sugerido")
    rec["importe_sugerido"] = round(float(importe_real), 2)
    rec["apuesta_real"] = True

    inicializar_db(db_path)
    guardar_recomendaciones([rec], db_path=db_path)

    with conectar(db_path) as conn:
        row = conn.execute("SELECT * FROM picks ORDER BY id DESC LIMIT 1").fetchone()

    return dict(row) if row else None


def marcar_apuesta_real_pick(
    pick_id: int,
    importe_real: float | None = None,
    db_path: str = DB_PATH,
) -> dict[str, Any] | None:
    inicializar_db(db_path)

    with conectar(db_path) as conn:
        row = conn.execute("SELECT * FROM picks WHERE id = ?", (pick_id,)).fetchone()

        if row is None:
            return None

        pick = dict(row)
        raw = _raw_pick(pick)
        importe = round(float(importe_real), 2) if importe_real is not None else round(float(pick.get("importe_sugerido") or 0), 2)

        if importe <= 0:
            raise ValueError("importe_real debe ser mayor que 0")

        raw["importe_modelo_sugerido"] = raw.get("importe_modelo_sugerido") or pick.get("importe_sugerido")
        raw["importe_sugerido"] = importe
        raw["apuesta_real"] = True

        conn.execute(
            """
            UPDATE picks
            SET importe_sugerido = ?,
                raw_json = ?
            WHERE id = ?
            """,
            (importe, json.dumps(raw, ensure_ascii=False), pick_id),
        )
        conn.commit()

        updated = conn.execute("SELECT * FROM picks WHERE id = ?", (pick_id,)).fetchone()

    return dict(updated) if updated else None


def actualizar_importe_pick(
    pick_id: int,
    importe_real: float,
    db_path: str = DB_PATH,
) -> dict[str, Any] | None:
    if importe_real <= 0:
        raise ValueError("importe_real debe ser mayor que 0")

    inicializar_db(db_path)

    with conectar(db_path) as conn:
        row = conn.execute("SELECT * FROM picks WHERE id = ?", (pick_id,)).fetchone()

        if row is None:
            return None

        raw = _raw_pick(dict(row))
        raw["importe_modelo_sugerido"] = raw.get("importe_modelo_sugerido") or row["importe_sugerido"]
        raw["importe_sugerido"] = round(float(importe_real), 2)
        raw["apuesta_real"] = True

        conn.execute(
            """
            UPDATE picks
            SET importe_sugerido = ?,
                raw_json = ?
            WHERE id = ?
            """,
            (round(float(importe_real), 2), json.dumps(raw, ensure_ascii=False), pick_id),
        )
        conn.commit()

        updated = conn.execute("SELECT * FROM picks WHERE id = ?", (pick_id,)).fetchone()

    return dict(updated)


def actualizar_cuota_pick(
    pick_id: int,
    cuota_real: float,
    db_path: str = DB_PATH,
) -> dict[str, Any] | None:
    if cuota_real <= 1:
        raise ValueError("cuota_real debe ser mayor que 1")

    inicializar_db(db_path)

    with conectar(db_path) as conn:
        row = conn.execute("SELECT * FROM picks WHERE id = ?", (pick_id,)).fetchone()

        if row is None:
            return None

        pick = dict(row)
        raw = _raw_pick(pick)
        raw["cuota_modelo_original"] = raw.get("cuota_modelo_original") or pick.get("cuota")
        raw["cuota_apuesta"] = round(float(cuota_real), 3)
        raw["apuesta_real"] = True

        profit_loss = pick.get("profit_loss")

        if pick.get("estado") == "cerrada" and pick.get("resultado"):
            importe = float(pick["importe_sugerido"] or 0)
            resultado = pick["resultado"]

            if resultado == "win":
                profit_loss = round(importe * (float(cuota_real) - 1), 2)
            elif resultado == "loss":
                profit_loss = round(-importe, 2)
            else:
                profit_loss = 0

        conn.execute(
            """
            UPDATE picks
            SET cuota = ?,
                profit_loss = ?,
                raw_json = ?
            WHERE id = ?
            """,
            (
                round(float(cuota_real), 3),
                profit_loss,
                json.dumps(raw, ensure_ascii=False),
                pick_id,
            ),
        )
        conn.commit()

        updated = conn.execute("SELECT * FROM picks WHERE id = ?", (pick_id,)).fetchone()

    return dict(updated)


def _pick_field(pick: dict[str, Any], field: str, default: Any = None) -> Any:
    raw = _raw_pick(pick)
    return raw.get(field, pick.get(field, default))


def _tier_priority(tier: str | None) -> int:
    return {
        "stakazo": 3,
        "elite": 2,
        "premium": 1,
        "seguimiento": 0,
        "descartable": 0,
    }.get(str(tier or "").lower(), 0)


def _prioridad_pick_tracking(pick: dict[str, Any]) -> tuple:
    return (
        _tier_priority(_pick_field(pick, "elite_tier", "")),
        float(_pick_field(pick, "quality_score", 0) or 0),
        float(_pick_field(pick, "reliability_score", 0) or 0),
        float(_pick_field(pick, "puntuacion_confianza", 0) or 0),
        float(_pick_field(pick, "valor_esperado", 0) or 0),
        int(pick.get("id") or 0),
    )


def listar_picks(
    limit: int = 100,
    estado: str | None = None,
    elite_tier: str | None = None,
    solo_elite: bool = False,
    solo_stakazos: bool = False,
    sport_label: str | None = None,
    league_label: str | None = None,
    min_quality_score: int | None = None,
    min_reliability_score: int | None = None,
    apuesta_real: bool | None = None,
    publicada_telegram: bool | None = None,
    order_by: str = "recientes",
    db_path: str = DB_PATH,
) -> list[dict[str, Any]]:
    inicializar_db(db_path)
    limit = max(1, min(limit, 500))

    with conectar(db_path) as conn:
        if estado:
            rows = conn.execute(
                "SELECT * FROM picks WHERE estado = ? ORDER BY id DESC",
                (estado,),
            ).fetchall()
        else:
            rows = conn.execute(
                "SELECT * FROM picks WHERE estado <> 'archivada' ORDER BY id DESC",
            ).fetchall()

    picks = [dict(row) for row in rows]

    if solo_stakazos:
        picks = [p for p in picks if str(_pick_field(p, "elite_tier", "")).lower() == "stakazo"]
    elif solo_elite:
        picks = [p for p in picks if bool(_pick_field(p, "elite_pick", False))]

    if elite_tier:
        picks = [p for p in picks if str(_pick_field(p, "elite_tier", "")).lower() == elite_tier.lower()]

    if sport_label:
        picks = [p for p in picks if str(_pick_field(p, "sport_label", "")).lower() == sport_label.lower()]

    if league_label:
        picks = [p for p in picks if str(_pick_field(p, "league_label", "")).lower() == league_label.lower()]

    if min_quality_score is not None:
        picks = [p for p in picks if float(_pick_field(p, "quality_score", 0) or 0) >= min_quality_score]

    if min_reliability_score is not None:
        picks = [p for p in picks if float(_pick_field(p, "reliability_score", 0) or 0) >= min_reliability_score]

    if apuesta_real is not None:
        picks = [p for p in picks if bool(_pick_field(p, "apuesta_real", False)) is apuesta_real]

    if publicada_telegram is not None:
        picks = [p for p in picks if bool(_pick_field(p, "telegram_publicada", False)) is publicada_telegram]

    if order_by == "premium":
        picks = sorted(picks, key=_prioridad_pick_tracking, reverse=True)
    else:
        picks = sorted(picks, key=lambda p: int(p.get("id") or 0), reverse=True)

    return picks[:limit]


def archivar_picks_pendientes(
    *,
    id_desde: int | None = None,
    id_hasta: int | None = None,
    db_path: str = DB_PATH,
) -> dict[str, Any]:
    inicializar_db(db_path)

    condiciones = ["estado = 'pendiente'"]
    params: list[Any] = []

    if id_desde is not None:
        condiciones.append("id >= ?")
        params.append(int(id_desde))
    if id_hasta is not None:
        condiciones.append("id <= ?")
        params.append(int(id_hasta))

    where_clause = " AND ".join(condiciones)

    with conectar(db_path) as conn:
        selected = conn.execute(
            f"SELECT id FROM picks WHERE {where_clause}",
            tuple(params),
        ).fetchall()
        affected_ids = [int(row["id"]) for row in selected]

        if affected_ids:
            conn.execute(
                f"UPDATE picks SET estado = 'archivada' WHERE {where_clause}",
                tuple(params),
            )
            conn.commit()

    return {
        "archivadas": len(affected_ids),
        "ids": affected_ids,
        "id_desde": id_desde,
        "id_hasta": id_hasta,
    }


def eliminar_picks_archivadas(
    *,
    id_desde: int | None = None,
    id_hasta: int | None = None,
    db_path: str = DB_PATH,
) -> dict[str, Any]:
    inicializar_db(db_path)

    condiciones = ["estado = 'archivada'"]
    params: list[Any] = []

    if id_desde is not None:
        condiciones.append("id >= ?")
        params.append(int(id_desde))
    if id_hasta is not None:
        condiciones.append("id <= ?")
        params.append(int(id_hasta))

    where_clause = " AND ".join(condiciones)

    with conectar(db_path) as conn:
        selected = conn.execute(
            f"SELECT id FROM picks WHERE {where_clause}",
            tuple(params),
        ).fetchall()
        affected_ids = [int(row["id"]) for row in selected]

        if affected_ids:
            placeholders = ", ".join("?" for _ in affected_ids)
            conn.execute(
                f"UPDATE telegram_publication_items SET pick_id = NULL WHERE pick_id IN ({placeholders})",
                tuple(affected_ids),
            )
            conn.execute(
                f"DELETE FROM pick_evaluations WHERE pick_id IN ({placeholders})",
                tuple(affected_ids),
            )
            conn.execute(
                f"DELETE FROM picks WHERE id IN ({placeholders})",
                tuple(affected_ids),
            )
            conn.commit()

    return {
        "eliminadas": len(affected_ids),
        "ids": affected_ids,
        "id_desde": id_desde,
        "id_hasta": id_hasta,
    }


def actualizar_resultado(
    pick_id: int,
    resultado: str,
    closing_odds: float | None = None,
    db_path: str = DB_PATH,
) -> dict[str, Any] | None:
    inicializar_db(db_path)
    resultado = resultado.lower().strip()

    if resultado not in {"win", "loss", "push"}:
        raise ValueError("resultado debe ser win, loss o push")

    with conectar(db_path) as conn:
        row = conn.execute("SELECT * FROM picks WHERE id = ?", (pick_id,)).fetchone()

        if row is None:
            return None

        pick = dict(row)
        importe = float(pick["importe_sugerido"] or 0)
        cuota = float(pick["cuota"] or 0)

        if resultado == "win":
            profit_loss = round(importe * (cuota - 1), 2)
        elif resultado == "loss":
            profit_loss = round(-importe, 2)
        else:
            profit_loss = 0

        conn.execute(
            """
            UPDATE picks
            SET estado = 'cerrada',
                resultado = ?,
                closing_odds = ?,
                profit_loss = ?
            WHERE id = ?
            """,
            (resultado, closing_odds, profit_loss, pick_id),
        )
        conn.commit()

        updated = conn.execute("SELECT * FROM picks WHERE id = ?", (pick_id,)).fetchone()
    updated_dict = dict(updated)
    resolved_closing = closing_odds

    if resolved_closing is None:
        resolved_closing = obtener_closing_odds_pick(pick_id, db_path=db_path)
        if resolved_closing is not None:
            with conectar(db_path) as conn:
                conn.execute(
                    "UPDATE picks SET closing_odds = ? WHERE id = ?",
                    (resolved_closing, pick_id),
                )
                conn.commit()
                refreshed = conn.execute("SELECT * FROM picks WHERE id = ?", (pick_id,)).fetchone()
                if refreshed is not None:
                    updated_dict = dict(refreshed)

    registrar_evaluacion_pick(
        pick_id=pick_id,
        resultado=resultado,
        closing_odds=resolved_closing,
        db_path=db_path,
    )

    return updated_dict


def registrar_publicacion_telegram(
    publication_type: str,
    payload: dict[str, Any],
    items: list[dict[str, Any]],
    db_path: str = DB_PATH,
) -> dict[str, Any]:
    inicializar_db(db_path)
    ahora = datetime.now(UTC).isoformat()

    with conectar(db_path) as conn:
        cursor = conn.execute(
            """
            INSERT INTO telegram_publications (
                created_at, publication_type, sport_label, league_label,
                total_picks, total_stakazos, payload_json
            )
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            (
                ahora,
                publication_type,
                payload.get("deporte"),
                payload.get("liga"),
                int(payload.get("total_elite") or 0),
                int(payload.get("total_stakazos") or 0),
                json.dumps(payload, ensure_ascii=False),
            ),
        )
        publication_id = int(cursor.lastrowid)

        for item in items:
            conn.execute(
                """
                INSERT INTO telegram_publication_items (
                    publication_id, pick_id, telegram_message_id, message_kind, text
                )
                VALUES (?, ?, ?, ?, ?)
                """,
                (
                    publication_id,
                    item.get("pick_id"),
                    item.get("telegram_message_id"),
                    item.get("message_kind") or "pick",
                    item.get("text") or "",
                ),
            )

            pick_id = item.get("pick_id")
            if pick_id:
                row = conn.execute("SELECT * FROM picks WHERE id = ?", (pick_id,)).fetchone()
                if row is not None:
                    pick = dict(row)
                    raw = _raw_pick(pick)
                    raw["telegram_publicada"] = True
                    raw["telegram_publication_id"] = publication_id
                    raw["telegram_message_id"] = item.get("telegram_message_id")
                    conn.execute(
                        "UPDATE picks SET raw_json = ? WHERE id = ?",
                        (json.dumps(raw, ensure_ascii=False), pick_id),
                    )

        conn.commit()

        row = conn.execute(
            "SELECT * FROM telegram_publications WHERE id = ?",
            (publication_id,),
        ).fetchone()

    return dict(row) if row else {
        "id": publication_id,
        "created_at": ahora,
        "publication_type": publication_type,
    }


def listar_publicaciones_telegram(limit: int = 20, db_path: str = DB_PATH) -> list[dict[str, Any]]:
    inicializar_db(db_path)
    limit = max(1, min(limit, 100))

    with conectar(db_path) as conn:
        publicaciones = conn.execute(
            "SELECT * FROM telegram_publications ORDER BY id DESC LIMIT ?",
            (limit,),
        ).fetchall()

        salida = []
        for row in publicaciones:
            publicacion = dict(row)
            payload = json.loads(publicacion.get("payload_json") or "{}")
            items = [
                dict(item)
                for item in conn.execute(
                    """
                    SELECT i.*, p.estado, p.resultado, p.partido, p.equipo, p.raw_json
                    FROM telegram_publication_items i
                    LEFT JOIN picks p ON p.id = i.pick_id
                    WHERE i.publication_id = ?
                    ORDER BY i.id ASC
                    """,
                    (publicacion["id"],),
                ).fetchall()
            ]
            pick_items = [
                item
                for item in items
                if item.get("message_kind") == "pick" and item.get("pick_id")
            ]
            ganadas = sum(1 for item in pick_items if item.get("resultado") == "win")
            perdidas = sum(1 for item in pick_items if item.get("resultado") == "loss")
            nulas = sum(1 for item in pick_items if item.get("resultado") == "push")
            pendientes = sum(1 for item in pick_items if item.get("estado") != "cerrada")

            salida.append(
                {
                    "id": publicacion["id"],
                    "created_at": publicacion["created_at"],
                    "publication_type": publicacion["publication_type"],
                    "sport_label": publicacion.get("sport_label"),
                    "league_label": publicacion.get("league_label"),
                    "total_picks": publicacion.get("total_picks"),
                    "total_stakazos": publicacion.get("total_stakazos"),
                    "payload": payload,
                    "items": items,
                    "resultado_resumen": {
                        "pendientes": pendientes,
                        "ganadas": ganadas,
                        "perdidas": perdidas,
                        "nulas": nulas,
                    },
                }
            )

    return salida


def _raw_pick(pick: dict[str, Any]) -> dict[str, Any]:
    try:
        return json.loads(pick.get("raw_json") or "{}")
    except json.JSONDecodeError:
        return {}


def _pick_odds_value(pick: dict[str, Any]) -> float | None:
    raw = _raw_pick(pick)
    for key in ("cuota", "cuota_apuesta", "cuota_real", "closing_odds"):
        value = pick.get(key)
        if value not in (None, "", 0, 0.0):
            try:
                return float(value)
            except (TypeError, ValueError):
                pass
        raw_value = raw.get(key)
        if raw_value not in (None, "", 0, 0.0):
            try:
                return float(raw_value)
            except (TypeError, ValueError):
                pass
    return None


def _pick_odds_bucket(pick: dict[str, Any]) -> str:
    return odds_bucket_for_value(_pick_odds_value(pick))


def _bool_pick_flag(pick: dict[str, Any], field: str, default: bool = False) -> bool:
    raw = _raw_pick(pick)
    value = raw.get(field, pick.get(field, default))
    return bool(value)


def _same_optional_float(left: Any, right: Any) -> bool:
    if left in {None, ""} and right in {None, ""}:
        return True
    try:
        return round(float(left), 4) == round(float(right), 4)
    except (TypeError, ValueError):
        return False


def _snapshot_matches_pick(snapshot: dict[str, Any], pick: dict[str, Any]) -> bool:
    raw_pick = _raw_pick(pick)
    raw_snapshot = _raw_pick(snapshot)
    outcome = raw_snapshot.get("outcome") or {}
    snapshot_description = outcome.get("description")
    pick_description = raw_pick.get("outcome_description")

    if str(snapshot.get("market_key") or "").strip().lower() != str(pick.get("mercado") or raw_pick.get("mercado") or "").strip().lower():
        return False

    if str(snapshot.get("outcome_name") or "").strip().lower() != str(raw_pick.get("equipo_raw") or raw_pick.get("equipo") or pick.get("equipo") or "").strip().lower():
        return False

    if not _same_optional_float(snapshot.get("outcome_point"), raw_pick.get("outcome_point")):
        return False

    if str(snapshot_description or "").strip().lower() != str(pick_description or "").strip().lower():
        return False

    return True


def obtener_closing_odds_pick(pick_id: int, db_path: str = DB_PATH) -> float | None:
    inicializar_db(db_path)

    with conectar(db_path) as conn:
        row = conn.execute("SELECT * FROM picks WHERE id = ?", (pick_id,)).fetchone()
        if row is None:
            return None

        pick = dict(row)
        event_id = pick.get("event_id")
        if not event_id:
            return None

        snapshot_rows = conn.execute(
            """
            SELECT * FROM odds_snapshots
            WHERE event_id = ?
            ORDER BY created_at DESC, id DESC
            """,
            (event_id,),
        ).fetchall()

    snapshots = [dict(item) for item in snapshot_rows]
    casa_pick = str(pick.get("casa") or "").strip().lower()

    for snapshot in snapshots:
        if str(snapshot.get("bookmaker") or "").strip().lower() != casa_pick:
            continue
        if _snapshot_matches_pick(snapshot, pick):
            try:
                return round(float(snapshot.get("price")), 3)
            except (TypeError, ValueError):
                return None

    for snapshot in snapshots:
        if _snapshot_matches_pick(snapshot, pick):
            try:
                return round(float(snapshot.get("price")), 3)
            except (TypeError, ValueError):
                return None

    return None


def registrar_evaluacion_pick(
    pick_id: int,
    resultado: str,
    closing_odds: float | None = None,
    db_path: str = DB_PATH,
) -> dict[str, Any] | None:
    inicializar_db(db_path)
    ahora = datetime.now(UTC).isoformat()

    with conectar(db_path) as conn:
        row = conn.execute("SELECT * FROM picks WHERE id = ?", (pick_id,)).fetchone()
        if row is None:
            return None

        pick = dict(row)
        raw = _raw_pick(pick)
        closing = closing_odds if closing_odds is not None else pick.get("closing_odds")
        price_taken = pick.get("cuota")
        clv_pct = None
        value_captured = None

        try:
            if closing and price_taken:
                clv_pct = round(((float(price_taken) / float(closing)) - 1) * 100, 2)
        except (TypeError, ValueError, ZeroDivisionError):
            clv_pct = None

        try:
            if raw.get("probabilidad_modelo") is not None and closing:
                value_captured = round((float(raw.get("probabilidad_modelo")) * float(closing)) - 1, 4)
        except (TypeError, ValueError):
            value_captured = None

        payload = {
            "pick_id": pick_id,
            "event_id": pick.get("event_id"),
            "partido": pick.get("partido"),
            "equipo": pick.get("equipo"),
            "resultado": resultado,
            "closing_odds": closing,
            "price_taken": price_taken,
            "clv_pct": clv_pct,
            "value_captured": value_captured,
            "quality_score": raw.get("quality_score", pick.get("quality_score")),
            "reliability_score": raw.get("reliability_score"),
            "execution_score": raw.get("execution_score"),
            "ranking_score": raw.get("ranking_score"),
            "elite_tier": raw.get("elite_tier"),
            "market_signal": raw.get("market_signal"),
            "recommended_by_bot": raw.get("recommended_by_bot", pick.get("recommended_by_bot", 1)),
            "auto_eval_eligible": raw.get("auto_eval_eligible", pick.get("auto_eval_eligible", 1)),
        }

        conn.execute(
            """
            INSERT INTO pick_evaluations (
                pick_id, created_at, event_id, sport_label, league_label, mercado, casa,
                resultado, closing_odds, price_taken, value_captured, clv_pct,
                quality_score, reliability_score, execution_score, ranking_score, elite_tier, payload_json
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(pick_id) DO UPDATE SET
                created_at = excluded.created_at,
                resultado = excluded.resultado,
                closing_odds = excluded.closing_odds,
                price_taken = excluded.price_taken,
                value_captured = excluded.value_captured,
                clv_pct = excluded.clv_pct,
                quality_score = excluded.quality_score,
                reliability_score = excluded.reliability_score,
                execution_score = excluded.execution_score,
                ranking_score = excluded.ranking_score,
                elite_tier = excluded.elite_tier,
                payload_json = excluded.payload_json
            """,
            (
                pick_id,
                ahora,
                pick.get("event_id"),
                pick.get("sport_label"),
                pick.get("league_label"),
                pick.get("mercado"),
                pick.get("casa"),
                resultado,
                closing,
                price_taken,
                value_captured,
                clv_pct,
                raw.get("quality_score", pick.get("quality_score")),
                raw.get("reliability_score"),
                raw.get("execution_score"),
                raw.get("ranking_score"),
                raw.get("elite_tier"),
                json.dumps(payload, ensure_ascii=False),
            ),
        )
        conn.commit()

        evaluation_row = conn.execute("SELECT * FROM pick_evaluations WHERE pick_id = ?", (pick_id,)).fetchone()

    return dict(evaluation_row) if evaluation_row else None


def _score_map(evento: dict[str, Any]) -> dict[str, int]:
    scores = {}

    for score in evento.get("scores") or []:
        name = score.get("name")
        value = score.get("score")

        if name is None or value is None:
            continue

        try:
            scores[name] = int(value)
        except (TypeError, ValueError):
            continue

    return scores


def _resultado_partido(home_score: int, away_score: int) -> str:
    if home_score > away_score:
        return "home"
    if away_score > home_score:
        return "away"
    return "draw"


def _resultado_pick_con_score(pick: dict[str, Any], evento: dict[str, Any]) -> str | None:
    raw = _raw_pick(pick)
    scores = _score_map(evento)
    home = evento.get("home_team")
    away = evento.get("away_team")

    if not home or not away or home not in scores or away not in scores:
        return None

    home_score = scores[home]
    away_score = scores[away]
    mercado = raw.get("mercado") or pick.get("mercado")
    nombre = raw.get("equipo_raw") or raw.get("equipo") or pick.get("equipo")
    tipo = raw.get("tipo_resultado_raw") or pick.get("tipo_resultado")
    point = raw.get("outcome_point")
    description = raw.get("outcome_description")

    try:
        point = float(point) if point is not None else None
    except (TypeError, ValueError):
        point = None

    if mercado == "h2h":
        return "win" if tipo == _resultado_partido(home_score, away_score) else "loss"

    if mercado in {"totals", "alternate_totals"}:
        if point is None:
            return None

        total = home_score + away_score

        if total == point:
            return "push"
        if nombre == "Over":
            return "win" if total > point else "loss"
        if nombre == "Under":
            return "win" if total < point else "loss"

    if mercado == "team_totals":
        if point is None or not description:
            return None

        team_score = scores.get(description)

        if team_score is None:
            return None
        if team_score == point:
            return "push"
        if nombre == "Over":
            return "win" if team_score > point else "loss"
        if nombre == "Under":
            return "win" if team_score < point else "loss"

    if mercado == "btts":
        ambos_marcan = home_score > 0 and away_score > 0

        if nombre == "Yes":
            return "win" if ambos_marcan else "loss"
        if nombre == "No":
            return "win" if not ambos_marcan else "loss"

    if mercado == "double_chance":
        resultado = _resultado_partido(home_score, away_score)
        nombre_resultado = {
            "home": home,
            "away": away,
            "draw": "Draw",
        }[resultado]
        opciones = [op.strip().lower() for op in str(nombre).split(" or ")]

        return "win" if nombre_resultado.lower() in opciones else "loss"

    return None


def liquidar_picks_con_scores(
    scores: list[dict[str, Any]],
    db_path: str = DB_PATH,
) -> dict[str, Any]:
    inicializar_db(db_path)
    eventos = {
        evento.get("id"): evento
        for evento in scores
        if evento.get("id") and evento.get("completed") is True
    }
    liquidados = []
    omitidos = []

    with conectar(db_path) as conn:
        picks = conn.execute("SELECT * FROM picks WHERE estado = 'pendiente'").fetchall()

    for row in picks:
        pick = dict(row)
        if not _bool_pick_flag(pick, "recommended_by_bot", True):
            omitidos.append({"pick_id": pick["id"], "motivo": "pick no recomendada por el bot"})
            continue
        if not _bool_pick_flag(pick, "auto_eval_eligible", True):
            omitidos.append({"pick_id": pick["id"], "motivo": "pick no elegible para autoevaluacion"})
            continue

        event_id = pick.get("event_id")
        evento = eventos.get(event_id)

        if not evento:
            omitidos.append({"pick_id": pick["id"], "motivo": "sin marcador final"})
            continue

        resultado = _resultado_pick_con_score(pick, evento)

        if resultado is None:
            omitidos.append({"pick_id": pick["id"], "motivo": "mercado no liquidable con marcador"})
            continue

        closing_odds = obtener_closing_odds_pick(int(pick["id"]), db_path=db_path)
        actualizado = actualizar_resultado(pick["id"], resultado, closing_odds=closing_odds, db_path=db_path)

        if actualizado:
            liquidados.append({
                "pick_id": pick["id"],
                "resultado": resultado,
                "partido": pick.get("partido"),
                "mercado": pick.get("mercado"),
                "closing_odds": closing_odds,
            })

    return {
        "liquidados": len(liquidados),
        "omitidos": len(omitidos),
        "detalle": liquidados,
        "omitidos_detalle": omitidos[:20],
        "scope": "solo_picks_recomendadas_por_el_bot",
    }


def _metricas_grupo(picks: list[dict[str, Any]]) -> dict[str, Any]:
    cerrados = [p for p in picks if p["estado"] == "cerrada"]
    apostado = round(sum(float(p["importe_sugerido"] or 0) for p in cerrados), 2)
    beneficio = round(sum(float(p["profit_loss"] or 0) for p in cerrados), 2)
    ganadas = sum(1 for p in cerrados if p["resultado"] == "win")
    perdidas = sum(1 for p in cerrados if p["resultado"] == "loss")
    nulas = sum(1 for p in cerrados if p["resultado"] == "push")
    quality_values = []
    reliability_values = []
    clv_values = []

    for pick in picks:
        raw = _raw_pick(pick)
        quality = raw.get("quality_score", pick.get("quality_score"))
        reliability = raw.get("reliability_score", pick.get("reliability_score"))

        if quality is not None:
            quality_values.append(float(quality))
        if reliability is not None:
            reliability_values.append(float(reliability))

    for pick in cerrados:
        cuota = pick.get("cuota")
        closing_odds = pick.get("closing_odds")

        if cuota and closing_odds:
            clv_values.append((float(cuota) / float(closing_odds)) - 1)

    return {
        "picks": len(picks),
        "cerradas": len(cerrados),
        "pendientes": len(picks) - len(cerrados),
        "ganadas": ganadas,
        "perdidas": perdidas,
        "nulas": nulas,
        "apostado": apostado,
        "beneficio": beneficio,
        "roi": round((beneficio / apostado) * 100, 2) if apostado else 0,
        "hit_rate": round((ganadas / len(cerrados)) * 100, 2) if cerrados else 0,
        "quality_media": round(sum(quality_values) / len(quality_values), 2) if quality_values else None,
        "reliability_media": round(sum(reliability_values) / len(reliability_values), 2) if reliability_values else None,
        "clv_medio": round((sum(clv_values) / len(clv_values)) * 100, 2) if clv_values else None,
        "clv_muestras": len(clv_values),
        "clv_positivo_pct": round((sum(1 for x in clv_values if x > 0) / len(clv_values)) * 100, 2) if clv_values else None,
    }


def listar_evaluaciones_picks(
    limit: int = 200,
    db_path: str = DB_PATH,
    apply_history_resets: bool = True,
) -> list[dict[str, Any]]:
    inicializar_db(db_path)
    limit = max(1, min(limit, 1000))

    with conectar(db_path) as conn:
        rows = conn.execute(
            "SELECT * FROM pick_evaluations ORDER BY id DESC LIMIT ?",
            (limit,),
        ).fetchall()

    evaluaciones = [dict(row) for row in rows]
    if apply_history_resets:
        evaluaciones = filtrar_registros_por_reset_deporte(evaluaciones, db_path=db_path)
    return evaluaciones


def resumen_calibracion_modelo(db_path: str = DB_PATH) -> dict[str, Any]:
    evaluaciones = listar_evaluaciones_picks(limit=2000, db_path=db_path)

    def agrupar_por_clave(clave: str) -> list[dict[str, Any]]:
        grupos: dict[str, list[dict[str, Any]]] = {}

        for item in evaluaciones:
            payload = json.loads(item.get("payload_json") or "{}")
            nombre = str(payload.get(clave) or item.get(clave) or "sin_dato")
            grupos.setdefault(nombre, []).append(item)

        salida = []
        for nombre, grupo in grupos.items():
            total = len(grupo)
            wins = sum(1 for row in grupo if row.get("resultado") == "win")
            losses = sum(1 for row in grupo if row.get("resultado") == "loss")
            pushes = sum(1 for row in grupo if row.get("resultado") == "push")
            clv_values = [float(row["clv_pct"]) for row in grupo if row.get("clv_pct") is not None]
            ranking_values = [float(row["ranking_score"]) for row in grupo if row.get("ranking_score") is not None]
            execution_values = [float(row["execution_score"]) for row in grupo if row.get("execution_score") is not None]
            value_captured_values = [float(row["value_captured"]) for row in grupo if row.get("value_captured") is not None]
            salida.append({
                "nombre": nombre,
                "muestra": total,
                "wins": wins,
                "losses": losses,
                "pushes": pushes,
                "hit_rate": round((wins / total) * 100, 2) if total else 0,
                "clv_medio": round(sum(clv_values) / len(clv_values), 2) if clv_values else None,
                "ranking_medio": round(sum(ranking_values) / len(ranking_values), 2) if ranking_values else None,
                "execution_medio": round(sum(execution_values) / len(execution_values), 2) if execution_values else None,
                "value_capturado_medio": round(sum(value_captured_values) / len(value_captured_values), 4) if value_captured_values else None,
            })

        return sorted(salida, key=lambda item: (item["muestra"], item["hit_rate"]), reverse=True)

    return {
        "total_evaluaciones": len(evaluaciones),
        "por_tier": agrupar_por_clave("elite_tier"),
        "por_mercado": agrupar_por_clave("mercado"),
        "por_liga": agrupar_por_clave("league_label"),
        "por_market_signal": agrupar_por_clave("market_signal"),
    }


def dashboard_data(db_path: str = DB_PATH) -> dict[str, Any]:
    inicializar_db(db_path)

    with conectar(db_path) as conn:
        rows = conn.execute("SELECT * FROM picks ORDER BY id DESC").fetchall()

    picks = filtrar_registros_por_reset_deporte(
        [dict(row) for row in rows],
        db_path=db_path,
        sport_getter=lambda pick: _raw_pick(pick).get("sport_label") or pick.get("sport_label"),
    )
    stakazos = [
        pick for pick in picks
        if str((_raw_pick(pick).get("elite_tier") or pick.get("elite_tier") or "")).lower() == "stakazo"
    ]
    elite = [
        pick for pick in picks
        if str((_raw_pick(pick).get("elite_tier") or pick.get("elite_tier") or "")).lower() == "elite"
    ]
    premium = [
        pick for pick in picks
        if str((_raw_pick(pick).get("elite_tier") or pick.get("elite_tier") or "")).lower() == "premium"
    ]
    seguimiento = [
        pick for pick in picks
        if str((_raw_pick(pick).get("elite_tier") or pick.get("elite_tier") or "seguimiento")).lower() == "seguimiento"
    ]

    def agrupar(campo: str) -> list[dict[str, Any]]:
        grupos: dict[str, list[dict[str, Any]]] = {}

        for pick in picks:
            raw = _raw_pick(pick)
            valor = raw.get(campo) or pick.get(campo) or "sin_dato"
            grupos.setdefault(str(valor), []).append(pick)

        salida = []
        for nombre, grupo in grupos.items():
            metricas = _metricas_grupo(grupo)
            metricas["nombre"] = nombre
            salida.append(metricas)

        return sorted(salida, key=lambda x: (x["cerradas"], x["beneficio"]), reverse=True)

    def agrupar_personalizado(
        resolver: Any,
        *,
        min_closed: int = 0,
        sort_mode: str = "default",
    ) -> list[dict[str, Any]]:
        grupos: dict[str, list[dict[str, Any]]] = {}

        for pick in picks:
            nombre = str(resolver(pick) or "sin_dato")
            grupos.setdefault(nombre, []).append(pick)

        salida = []
        for nombre, grupo in grupos.items():
            metricas = _metricas_grupo(grupo)
            if int(metricas.get("cerradas") or 0) < min_closed:
                continue
            metricas["nombre"] = nombre
            salida.append(metricas)

        if sort_mode == "risk":
            return sorted(
                salida,
                key=lambda x: (
                    x["roi"],
                    x["hit_rate"],
                    x["beneficio"],
                    -x["cerradas"],
                ),
            )

        return sorted(salida, key=lambda x: (x["cerradas"], x["beneficio"]), reverse=True)

    por_liga_mercado = agrupar_personalizado(
        lambda pick: f"{str(_raw_pick(pick).get('league_label') or pick.get('league_label') or 'sin_liga')} :: {str(_raw_pick(pick).get('mercado') or pick.get('mercado') or 'sin_mercado')}",
        min_closed=1,
        sort_mode="risk",
    )
    por_rango_cuota = agrupar_personalizado(_pick_odds_bucket, min_closed=1, sort_mode="risk")
    peores_segmentos = {
        "liga_mercado": [
            row for row in por_liga_mercado
            if int(row.get("cerradas") or 0) >= 4
        ][:8],
        "mercado": [
            row for row in agrupar("mercado")
            if int(row.get("cerradas") or 0) >= 5
        ],
        "rango_cuota": [
            row for row in por_rango_cuota
            if int(row.get("cerradas") or 0) >= 4
        ][:6],
    }
    acciones_urgentes: list[str] = []
    for row in peores_segmentos["liga_mercado"][:3]:
        acciones_urgentes.append(
            f"Recortar o bloquear {row['nombre']} (ROI {row['roi']:.2f}%, hit {row['hit_rate']:.2f}%, {row['cerradas']} cerradas)."
        )
    for row in peores_segmentos["rango_cuota"][:2]:
        acciones_urgentes.append(
            f"Revisar cuotas {row['nombre']} (ROI {row['roi']:.2f}%, hit {row['hit_rate']:.2f}%)."
        )

    return {
        "resumen": estadisticas(db_path=db_path),
        "aprendizaje": aprendizaje(db_path=db_path),
        "calibracion": resumen_calibracion_modelo(db_path=db_path),
        "por_deporte": agrupar("sport_label"),
        "por_liga": agrupar("league_label"),
        "por_mercado": agrupar("mercado"),
        "por_casa": agrupar("casa"),
        "por_perfil": agrupar("perfil"),
        "por_modelo": agrupar("modelo_mercado"),
        "por_elite": agrupar("elite_tier"),
        "por_liga_mercado": por_liga_mercado,
        "por_rango_cuota": por_rango_cuota,
        "solo_stakazos": _metricas_grupo(stakazos),
        "solo_elite": _metricas_grupo(elite),
        "solo_premium": _metricas_grupo(premium),
        "solo_seguimiento": _metricas_grupo(seguimiento),
        "pendientes": [p for p in picks if p["estado"] == "pendiente"][:20],
        "auditoria_modelo": {
            "peores_segmentos": peores_segmentos,
            "acciones_urgentes": acciones_urgentes[:6],
        },
    }


def _evaluar_penalizacion_historica(metricas: dict[str, Any]) -> dict[str, Any] | None:
    cerradas = int(metricas.get("cerradas") or 0)

    if cerradas < 5:
        return None

    score = 0
    razones = []
    roi = float(metricas.get("roi") or 0)
    hit_rate = float(metricas.get("hit_rate") or 0)
    clv_medio = metricas.get("clv_medio")
    clv_positivo_pct = metricas.get("clv_positivo_pct")
    clv_muestras = int(metricas.get("clv_muestras") or 0)

    if roi <= -8:
        score += 12
        razones.append("ROI muy negativo")
    elif roi < 0:
        score += 6
        razones.append("ROI negativo")

    if clv_medio is not None:
        clv_medio = float(clv_medio)
        if clv_medio <= -3:
            score += 10
            razones.append("CLV muy negativo")
        elif clv_medio < 0:
            score += 5
            razones.append("CLV negativo")

    if cerradas >= 8 and hit_rate < 45:
        score += 4
        razones.append("Hit rate flojo")

    if clv_muestras >= 4 and clv_positivo_pct is not None and float(clv_positivo_pct) < 45:
        score += 4
        razones.append("Poco CLV positivo")

    if score < 8:
        return None

    if score >= 18:
        level = "alta"
    elif score >= 12:
        level = "media"
    else:
        level = "moderada"

    return {
        "penalty_score": score,
        "level": level,
        "reasons": razones,
        "sample_closed": cerradas,
    }


def _recent_clv_streak_penalty(
    rows: list[dict[str, Any]],
    *,
    min_streak: int = 3,
) -> dict[str, Any] | None:
    negatives: list[float] = []

    for row in rows:
        clv_raw = row.get("clv_pct")
        if clv_raw is None:
            continue
        clv = float(clv_raw)
        if clv < 0:
            negatives.append(clv)
            continue
        break

    streak = len(negatives)
    if streak < min_streak:
        return None

    avg_negative = sum(negatives) / streak if negatives else 0.0
    score = 0
    reasons = []

    if streak >= 5 and avg_negative <= -2.5:
        score += 14
        reasons.append("Racha CLV muy negativa reciente")
    elif streak >= 4 and avg_negative <= -1.75:
        score += 10
        reasons.append("Racha CLV negativa reciente")
    elif streak >= 3 and avg_negative <= -1.0:
        score += 6
        reasons.append("Inicio de deriva CLV reciente")

    if score == 0:
        return None

    level = "alta" if score >= 14 else "media" if score >= 10 else "moderada"
    return {
        "penalty_score": score,
        "level": level,
        "reasons": reasons,
        "streak_size": streak,
        "streak_avg_clv": round(avg_negative, 2),
    }


def _build_league_market_key(league: str, market: str) -> str:
    return f"{league}::{market}"


def _penalizaciones_por_racha_clv(
    *,
    db_path: str = DB_PATH,
) -> dict[str, dict[str, Any]]:
    evaluaciones = listar_evaluaciones_picks(limit=5000, db_path=db_path)
    grouped: dict[str, list[dict[str, Any]]] = {}

    for item in evaluaciones:
        payload = json.loads(item.get("payload_json") or "{}")
        league = str(payload.get("league_label") or item.get("league_label") or "sin_liga")
        market = str(payload.get("mercado") or item.get("mercado") or "sin_mercado")
        combo = _build_league_market_key(league, market)
        grouped.setdefault(combo, []).append(item)

    penalties: dict[str, Any] = {}
    for combo, rows in grouped.items():
        penalty = _recent_clv_streak_penalty(rows)
        if penalty:
            penalties[combo] = penalty

    return penalties


def penalizaciones_historicas(db_path: str = DB_PATH) -> dict[str, dict[str, Any]]:
    data = dashboard_data(db_path=db_path)
    ligas: dict[str, Any] = {}
    ligas_mercados: dict[str, Any] = {}
    tiers: dict[str, Any] = {}

    for fila in data["por_liga"]:
        evaluacion = _evaluar_penalizacion_historica(fila)
        if evaluacion:
            ligas[str(fila["nombre"])] = evaluacion

    for fila in data["por_elite"]:
        evaluacion = _evaluar_penalizacion_historica(fila)
        if evaluacion:
            tiers[str(fila["nombre"])] = evaluacion

    # Construir penalizaciones por combinacion liga + mercado usando picks cerrados
    with conectar(db_path) as conn:
        rows = conn.execute("SELECT * FROM picks ORDER BY id DESC").fetchall()
    picks = filtrar_registros_por_reset_deporte(
        [dict(row) for row in rows],
        db_path=db_path,
        sport_getter=lambda pick: _raw_pick(pick).get("sport_label") or pick.get("sport_label"),
    )
    grouped_combo: dict[str, list[dict[str, Any]]] = {}
    for pick in picks:
        league = str((_raw_pick(pick).get("league_label") or pick.get("league_label") or "sin_liga"))
        market = str((_raw_pick(pick).get("mercado") or pick.get("mercado") or "sin_mercado"))
        combo = _build_league_market_key(league, market)
        grouped_combo.setdefault(combo, []).append(pick)

    for combo, combo_picks in grouped_combo.items():
        evaluacion = _evaluar_penalizacion_historica(_metricas_grupo(combo_picks))
        if evaluacion:
            ligas_mercados[combo] = evaluacion

    # Sumar penalizaciones rapidas por racha de CLV reciente
    for combo, drift_penalty in _penalizaciones_por_racha_clv(db_path=db_path).items():
        base_penalty = ligas_mercados.get(combo)
        if base_penalty is None:
            ligas_mercados[combo] = drift_penalty
            continue

        merged_reasons = list(base_penalty.get("reasons", [])) + [
            reason for reason in drift_penalty.get("reasons", []) if reason not in base_penalty.get("reasons", [])
        ]
        merged_score = int(base_penalty.get("penalty_score") or 0) + int(drift_penalty.get("penalty_score") or 0)
        ligas_mercados[combo] = {
            **base_penalty,
            "penalty_score": merged_score,
            "level": "alta" if merged_score >= 18 else "media" if merged_score >= 12 else "moderada",
            "reasons": merged_reasons,
            "clv_drift_streak": drift_penalty.get("streak_size"),
            "clv_drift_avg": drift_penalty.get("streak_avg_clv"),
        }

    return {
        "ligas": ligas,
        "ligas_mercados": ligas_mercados,
        "tiers": tiers,
    }


def estadisticas(db_path: str = DB_PATH) -> dict[str, Any]:
    inicializar_db(db_path)

    with conectar(db_path) as conn:
        rows = conn.execute("SELECT * FROM picks WHERE estado = 'cerrada'").fetchall()
        pendientes = conn.execute("SELECT COUNT(*) AS total FROM picks WHERE estado = 'pendiente'").fetchone()["total"]
        snapshots = conn.execute("SELECT COUNT(*) AS total FROM odds_snapshots").fetchone()["total"]

    cerradas = [dict(row) for row in rows]
    total_cerradas = len(cerradas)
    total_apostado = round(sum(float(x["importe_sugerido"] or 0) for x in cerradas), 2)
    beneficio = round(sum(float(x["profit_loss"] or 0) for x in cerradas), 2)
    ganadas = sum(1 for x in cerradas if x["resultado"] == "win")
    perdidas = sum(1 for x in cerradas if x["resultado"] == "loss")
    nulas = sum(1 for x in cerradas if x["resultado"] == "push")
    roi = round((beneficio / total_apostado) * 100, 2) if total_apostado else 0

    clv_values = []
    for pick in cerradas:
        cuota = pick.get("cuota")
        closing_odds = pick.get("closing_odds")

        if cuota and closing_odds:
            clv_values.append((float(cuota) / float(closing_odds)) - 1)

    clv_medio = round((sum(clv_values) / len(clv_values)) * 100, 2) if clv_values else None

    return {
        "picks_cerrados": total_cerradas,
        "picks_pendientes": pendientes,
        "snapshots_cuotas": snapshots,
        "ganadas": ganadas,
        "perdidas": perdidas,
        "nulas": nulas,
        "hit_rate": round((ganadas / total_cerradas) * 100, 2) if total_cerradas else 0,
        "total_apostado": total_apostado,
        "beneficio": beneficio,
        "roi": roi,
        "clv_medio": clv_medio,
        "aviso": "No subas stake hasta tener una muestra amplia y CLV positivo.",
    }


def aprendizaje(db_path: str = DB_PATH) -> dict[str, Any]:
    inicializar_db(db_path)

    with conectar(db_path) as conn:
        picks = conn.execute("SELECT * FROM picks").fetchall()
        snapshots_total = conn.execute("SELECT COUNT(*) AS total FROM odds_snapshots").fetchone()["total"]
        eventos = conn.execute(
            "SELECT COUNT(DISTINCT event_id) AS total FROM odds_snapshots WHERE event_id IS NOT NULL"
        ).fetchone()["total"]
        casas = conn.execute(
            "SELECT COUNT(DISTINCT bookmaker) AS total FROM odds_snapshots WHERE bookmaker IS NOT NULL"
        ).fetchone()["total"]

    picks = [dict(row) for row in picks]
    cerrados = [p for p in picks if p["estado"] == "cerrada"]
    pendientes = [p for p in picks if p["estado"] == "pendiente"]
    con_clv = [p for p in cerrados if p.get("closing_odds")]
    evaluaciones = listar_evaluaciones_picks(limit=5000, db_path=db_path)
    clv_positivo = 0

    for pick in con_clv:
        cuota = pick.get("cuota")
        cierre = pick.get("closing_odds")

        if cuota and cierre and float(cuota) > float(cierre):
            clv_positivo += 1

    return {
        "snapshots_guardados": snapshots_total,
        "eventos_observados": eventos,
        "casas_observadas": casas,
        "picks_totales": len(picks),
        "picks_pendientes": len(pendientes),
        "picks_cerrados": len(cerrados),
        "picks_evaluadas": len(evaluaciones),
        "training_samples": len(evaluaciones),
        "picks_con_clv": len(con_clv),
        "porcentaje_clv_positivo": round((clv_positivo / len(con_clv)) * 100, 2) if con_clv else 0,
        "calibracion": resumen_calibracion_modelo(db_path=db_path),
        "lectura": (
            "Todavía falta muestra para aprender con fiabilidad."
            if len(cerrados) < 30
            else "Ya hay una muestra inicial; revisa ROI y CLV antes de subir riesgo."
        ),
    }
